### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by vonProteus** [mansuf/mangadex-downloader#107]
### The idea

can you add creating of docker image (x64 arm and arm64) to your build ci?

### Why this feature should be added to the app ?

docker is convenient 
and it would god start for k8s jobs

**Comment by vonProteus** [comment]
something like this would be sufficient 
https://github.com/vonProteus/mangadex-downloader-docker
https://hub.docker.com/r/vonproteus/mangadex-downloader-docker
and i would like to switch to official image when it will be available

**Comment by mansuf** [comment]
Yes, i will add it to my build CI soon and i will use your docker image as a reference, thank you for this !

**Comment by mansuf** [comment]
Docker image added in https://hub.docker.com/r/mansuf/mangadex-downloader, tag `latest` (v2.10.3)

**Comment by mansuf** [comment]
About the increased size docker image, now `latest` tag has reduced size, but it doesn't have optional features. If you want to use optional features, you can install from `latest-optional` tag

Previously, it was almost 1GB (800MB - 900MB) size for a compressed docker image. And now it was 400MB 

![image](https://github.com/mansuf/mangadex-downloader/assets/43638783/5bd738e9-177a-4581-a340-9e8c758b2e37)

**Comment by rokibhasansagar** [comment]
@mansuf, Wouldn't it be better to use Alpine Linux for the base image of Docker? It would reduce the image size too.

**Comment by mansuf** [comment]
> Wouldn't it be better to use Alpine Linux for the base image of Docker? It would reduce the image size too.

I agree, but if i want to use alpine linux as base image, then the supported OS/ARCH will be reduced too for `optional` tags. I tested it out myself and the results is the image only support for `amd64` and `arm64`. The `arm/v7` doesn't included (because it throws error when installing rust compiler, saying it doesn't have binaries for that cpu architecture).

I guess i can use alpine linux as base image for non-optional tags, but other than that i think i will keep debian as base image.

**Comment by mansuf** [comment]
Base image for non-optional tags are now using alpine linux https://github.com/mansuf/mangadex-downloader/commit/71b4697cdb4bb1d607f71d1cbcc9b7eeb2772857 https://github.com/mansuf/mangadex-downloader/commit/ff679924096d6d0a76e16d25b6842ba134c471f4

![image](https://github.com/user-attachments/assets/56016a7f-e0b6-43df-b1bd-8b8f57a1f772)
