### ISSUE TITLE
[Feature Request] Optional flag to add chapter title to file name

### ISSUE THREAD

**Issue by TechnologyMan101** [mansuf/mangadex-downloader#12]
Would it be possible for this program to have an **optional** flag to add the chapter title to the final file name? I feel that such a feature would be useful for certain file organizing schemes. Of course, this should be optional because there are bound to be many chapters with long titles.

**Comment by mansuf** [comment]
Yes, it is possible to have this optional feature if it's related to file management.

However, format like `cbz-single` and `pdf-single` must put chapter title to "beginning of the chapter" image. Which is **required** feature not **optional**.

Well, i have to rework chapter naming system in order to get this done. Anyway, thanks for the idea !

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/commit/2569df05b2d1e3b86e0f2dc993c253c19ae6f49d
