### ISSUE TITLE
[Feature Request] Option to download only specific chapters

### ISSUE THREAD

**Issue by rohan-gt** [mansuf/mangadex-downloader#3]
It would be useful to have a `chapters` parameter in the `MangaDex.download()` function which allows the user to pass a list of specific chapters to download

**Comment by mansuf** [comment]
### Sorry for late reply

I cannot guarantee that this will be patched in next release. Because the base codes really out of update and need to do lot of rework (The base codes using MangaDex v3, meanwhile the MangaDex v3 is dead and MangaDex v5 is born). Right now I'm busy for school and some other projects that i have working on, maybe this will be added if i have free time.

**Comment by mansuf** [comment]
This feature exist in `v0.2.0`.

Sorry for very late update.
