### ISSUE TITLE
Batch script to download all new (or unread) chapters for all followed manga

### ISSUE THREAD

**Issue by Neoakb** [mansuf/mangadex-downloader#39]
### The idea

So I can use --save-as raw-volume --start-chapter ## --no-chapter-info --login

I've went ahead and downloaded everything that is out for all the manga I currently read. I would like to make a "download updates" batch script to just grab the newest stuff. Currently all the manga is set to "completed" in MD, which IIRC should update to "reading" when a new chapter comes out. Could the script login, then grab all the latest for whatever is marked as unread, download it all as a raw-volume, then mark it all as read?

I hope I explained this right lol

Thanks for a great tool!!!!

### Why this feature should be added to the app ?

Because I love you.

**Comment by mansuf** [comment]
> Could the script login, then grab all the latest for whatever is marked as unread, download it all as a raw-volume, then mark it all as read?

yes

> Because I love you.

no

------

Jk, i will add this to next release. Currently waiting new authentication system for developers to be released. I will work on this after new authentication system has been implemented fully. Hopefully, it didn't take long time.

**Comment by officialdevjackson** [comment]
Even adding a --latest option would be great too. I would love to see a feature that simply pulls the newest chapter available, with no login or anything.

**Comment by mansuf** [comment]
I should give an update for this issue, it's been a month since this issue opened. 

MangaDex is still not opened their OAuth2 registration yet. I cannot testing further if the new authentication system for developers is not yet released and i just wanna finish implement the new authentication system.

While i was waiting, i have reworked how the app download the latest chapters (see https://github.com/mansuf/mangadex-downloader/commit/865b7f5988a9cd92e21112ac8649a29299b5023f for more info). It's should properly handle latest chapters regardless what the formats is (either chapters, volumes, or single). So you don't have to worry about latest chapters are not being downloaded and you have to delete files (if you're using volume or single formats) or use `--replace` if you want to download latest chapters.

If you want to try it, you can install development version:

```
pip install git+https://github.com/mansuf/mangadex-downloader.git@e70eab960c25b61bbd6a317bc2ec2f08cc5d67a2
```

**Note**: this is the latest stable patch from development version, if you have issue while running development version. You can open another issue.

>  Could the script login, then grab all the latest for whatever is marked as unread, download it all as a raw-volume, then mark it all as read?

As for this, i have been working on it. So it should finish this week. I cannot promise though, sometimes life can give you unexpected things :)

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/commit/2533e5b5b5c10d3182746218564ec1298497111e

You can try install development version, if you want to try it early

```
pip install git+https://github.com/mansuf/mangadex-downloader.git@2533e5b5b5c10d3182746218564ec1298497111e
```

You can access the feature by using `--download-mode` option with value `unread`. Oh and you must login in to use the feature.

```sh
mangadex-dl "https://mangadex.org/title/a96676e5-8ae2-425e-b549-7f15dd34a6d8" --login --download-mode "unread"
# You will be prompted to enter username and password for login
```
