### ISSUE TITLE
Can I know how to get Direct Download Links from your API?

### ISSUE THREAD

**Issue by missemily22** [mansuf/mangadex-downloader#42]

**Comment by mansuf** [comment]
Technically, you can use mangadex-downloader API, but it was intended for internal use (for CLI app) after [v2.0.0](https://github.com/mansuf/mangadex-downloader/releases/tag/v2.0.0). Because any changes can be made in the library without any notices. So your application might be broken if you update more often. 

You can use public API from MangaDex itself without relying mangadex-downloader library. The minimum requirement you need is HTTP library (like [requests](https://github.com/psf/requests)). [See here for more info](https://api.mangadex.org/)
