### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by TokuNiArimasen** [mansuf/mangadex-downloader#43]
File "C:\Users\Apricot\AppData\Roaming\Python\Python37\site-packages\mangadex_downloader\downloader.py", line 217, in _report
    if resp.headers.get('x-cache').startswith('HIT'):
AttributeError: 'NoneType' object has no attribute 'startswith'

getting this error when trying to download manga, any help?
this was the manga page i tried downloading from, it downloads the cover correctly but not the next pages:
https://mangadex.org/title/ada3dca4-fdae-42ca-b867-dae6b860edec/isekai-furin

**Comment by mansuf** [comment]
Duplicate issue #18.

This bug was fixed in [v1.0.1](https://github.com/mansuf/mangadex-downloader/releases/tag/v1.0.1). Update your mangadex-downloader.

I see you're using Python 3.7, Python v3.7.x is no longer supported by mangadex-downloader after [v0.5.0](https://github.com/mansuf/mangadex-downloader/releases/tag/v0.5.0). You might wanna update your Python runtime to 3.8 or upper before updating mangadex-downloader.

Or if you don't wanna update your Python runtime, you can try download bundled executable (since you're in windows). But that require extra step (like add the binary directory to `PATH` environment variables, in order `mangadex-dl` command to work globaly on command prompt).

![image](https://user-images.githubusercontent.com/43638783/213379852-b2da9d44-1609-4bec-96d1-51a8d8f10a5a.png)
