### ISSUE TITLE
--login not passing creds correctly

### ISSUE THREAD

**Issue by Neoakb** [mansuf/mangadex-downloader#50]
### What happened ?

```
PS Y:\Books> .\mangadex-dl_x64_v2.7.1\mangadex-dl\mangadex-dl.exe --login
MangaDex username / email => neonfire
MangaDex password =>
[INFO] Logging in to MangaDex
[ERROR] Login to MangaDex failed, reason: User / Password does not match
[ERROR] User / Password does not match
PS Y:\Books>
```

I just tried the saved pass I had, then went and reset it as well. Waited after reset before trying again. Just won't work. I can log out and back in of MD's website without issue. Also tried with the --login-username --login-password options

### What did you expect to happen ?

to log in

### OS version

Win 11

### App version

x64-v2.7.1

### Installation origin

Github releases

### Reproducible command

.\mangadex-dl_x64_v2.7.1\mangadex-dl\mangadex-dl.exe --login

**Comment by mansuf** [comment]
If i remember correctly, MangaDex changed their authentication system on 17 December 2022. So if you changed your password after that date, your new password won't work in the application. Because OAuth2 (the new auth system) client registration for third-party applications are not open yet. And thus mangadex-downloader are using legacy authentication. 

Also if you're using a new account created after that date, it doesn't work too. I suggest try to use your old password.

**Comment by Neoakb** [comment]
Ah, I hadn't had the account before that date, so it looks like it won't
work for me. That's a real shame.

Thanks for the info.
