### ISSUE TITLE
Environment `MANGADEXDL_ZIP_COMPRESSION_LEVEL` is not working

### ISSUE THREAD

**Issue by NLZ** [mansuf/mangadex-downloader#59]
### What happened ?

I'm trying to make the cbz format use some compression (because default is no compression, deflated : 0), but despite setting the MANGADEXDL_ZIP_COMPRESSION_LEVEL environment variable, nothing happens.

### What did you expect to happen ?

I expected it to use the configured compression level, yet nothing happens.

### OS version

Win10

### App version

mangadex-downloader v2.8.3 (https://github.com/mansuf/mangadex-downloader)
Python: 3.10.10
arch: x64
bundled executable: yes

### Installation origin

Github releases

### Reproducible command

in cmd:
set MANGADEXDL_ZIP_COMPRESSION_LEVEL=1
mangadex-dl.exe https://mangadex.org/chapter/9f20eb08-abe9-4fb6-acde-5f85049fe24d --save-as cbz

Same results with setting it as permanent env var.

### Additional context

Why is no compression even the default? Deflated level 1 is producing a noticeable difference with jpegs (like 230kb -> 191kb), while higher levels doesn't do much (deflated L9 189kb, other compression type are also similar).
I'd guess that deflated level 1 has negligible impact on compression and decompression speeds, and there are no compatibility issues either, I don't see drawbacks with it.

So I'm not sure what the issue is with reading the env variable or how easy it would be fix, but adding compression by default or at least as a parameter would be also helpful.

**Comment by mansuf** [comment]
I forgot to put example usage in the docs how to use compression for cbz and epub formats, sorry about that.

Basically, you need to set 2 environments to enable compression

- `MANGADEXDL_ZIP_COMPRESSION_TYPE`
- `MANGADEXDL_ZIP_COMPRESSION_LEVEL`

By default, `MANGADEXDL_ZIP_COMPRESSION_TYPE` is set to `stored` which means the archive is not compressed at all. So you need to set it to other than `stored` (deflated, bzip2, lzma)

```batch
set MANGADEXDL_ZIP_COMPRESSION_TYPE=deflated
set MANGADEXDL_ZIP_COMPRESSION_LEVEL=1
mangadex-dl.exe "https://mangadex.org/chapter/9f20eb08-abe9-4fb6-acde-5f85049fe24d" --save-as cbz
```

As you seen in the docs, if you set `MANGADEXDL_ZIP_COMPRESSION_TYPE` to `lzma`, environment `MANGADEXDL_ZIP_COMPRESSION_LEVEL` has no effect at all.

```batch
set MANGADEXDL_ZIP_COMPRESSION_TYPE=lzma
mangadex-dl.exe "https://mangadex.org/chapter/9f20eb08-abe9-4fb6-acde-5f85049fe24d" --save-as cbz
```

> Why is no compression even the default? Deflated level 1 is producing a noticeable difference with jpegs (like 230kb -> 191kb), while higher levels doesn't do much (deflated L9 189kb, other compression type are also similar).
I'd guess that deflated level 1 has negligible impact on compression and decompression speeds, and there are no compatibility issues either, I don't see drawbacks with it.

The reason i did this because some systems may not have required modules to do compression stuff. Maybe you thinking that you have all requirements, but i'm thinking about the other users. Also it saves time for me to debug errors.

**Comment by NLZ** [comment]
Ah thanks, specifying both `MANGADEXDL_ZIP_COMPRESSION_TYPE` and `MANGADEXDL_ZIP_COMPRESSION_LEVEL` indeed works.
