### ISSUE TITLE
add flag --filename and make support imported as library

### ISSUE THREAD

**Issue by zYxDevs** [mansuf/mangadex-downloader#67]
### The idea

- add --filename flag so people can choose path to download and filename.
- add support mangadex-dl to imported as python library

### Why this feature should be added to the app ?

- make people more easy to use mangadex-dl

**Comment by mansuf** [comment]
> add --filename flag so people can choose path to download and filename.

If you want to use custom path then use `--path` option. Or did you mean you want an option to change manga folder name ?

> add support mangadex-dl to imported as python library

Starting v2.0.0, mangadex-downloader doesn't have public API anymore. There reasons for that, see below

- This is CLI (Command-Line Interface) application and most of the users are using CLI rather than API. So i have no intention to continue it anymore
- Even if i want to continue to expose public API. The whole code needs to be reworked and it cause a lot of times and efforts, i don't want that. This is just hobby project, nothing serious. I only worked on this project when i really-really have free time.

Of course, you can dive to the code itself and start using some of functions and classes that are not intended for public use. I'm not forcing you to not use the private API. But i must warned you that the code itself can be changed without any notice. So if you upgrade the package, the current script that you use may be broke.

**Comment by zYxDevs** [comment]
> 

yes even when used -d flags downloaded file will be on a folder with the manga title. i want to change manga folder name.

**Comment by mansuf** [comment]
I added this feature in [v3.0.0 branch](https://github.com/mansuf/mangadex-downloader/tree/v3.0.0) (commit https://github.com/mansuf/mangadex-downloader/commit/3698cf10aa22c14e1225000bffbff4f2a3b55c2e)

You can start trying it now by installing development version (v3.0.0 branch) 

Installation with git + pip:

```
pip uninstall mangadex-downloader
pip install git+https://github.com/mansuf/mangadex-downloader.git@3698cf10aa22c14e1225000bffbff4f2a3b55c2e
```

If you're installing mangadex-downloader from github releases, you can download the development version in here:

The download files are available in "artifacts" section

https://github.com/mansuf/mangadex-downloader/actions/runs/7249594589/

-------

Example usage:
```shell
# This will download to directory "/home/sussyuser/manga/Some manga title/"
# with filename "Vol. insert_volume_here Ch. insert_chapter_here.cbz"
mangadex-dl "URL" --path "/home/sussyuser/manga/{manga.title}" -f cbz --filename-chapter "Vol.{chapter.volume} Ch.{chapter.chapter}{file_ext}"
```

For more information about path placeholders, you can read the documentation here -> https://mangadex-dl.mansuf.link/en/v3.0.0/cli_ref/path_placeholders.html

If you have a problem, issue or bug, you can re-open and comment in this issue tracker here.
