### ISSUE TITLE
Some manga URLs don't get downloaded correctly

### ISSUE THREAD

**Issue by ahmadi3d** [mansuf/mangadex-downloader#81]
### What happened ?

I tried downloading the following URL: 
https://mangadex.org/title/1593cc24-e67a-411e-8e30-eec88a5ee670/red-storm
But the most of the images are from different mangas!

### What did you expect to happen ?

I wanted to only download the link I mentioned.

### OS version

Windows

### App version

2.10.1

### Installation origin

Github releases

### Reproducible command

Simply try downloading the following URL, take a look at the images that are downloaded and you can see the problem:
https://mangadex.org/title/1593cc24-e67a-411e-8e30-eec88a5ee670/red-storm

**Comment by mansuf** [comment]
> But the most of the images are from different mangas!

What chapter did cause the problem and what `--language` did you use ? Did you try to compare the images from MangaDex website and the downloaded one ?

If the compare results are same, then the problem is in the chapters itself. You must contact MangaDex to get fixed. Join their Discord and goto `#support` channel to report the issue.
