### ISSUE TITLE
Epub-volume doesn't add cover art

### ISSUE THREAD

**Issue by dalnew** [mansuf/mangadex-downloader#91]
### What happened ?

Seems to matter what options I choose volume covers won't be added to epub-volumes. There are volume covers present from the volumes I was trying to create. It creates everything correctly but doesn't use the volume cover art present here:
https://mangadex.org/title/a2c1d849-af05-4bbc-b2a7-866ebb10331f/one-piece-digital-colored-comics?tab=art

Seems only Japanese covers are present so I tried adding the -uvc Japanese option but that doesn't do anything. 

I am able to download the covers by manually running:
mangadex-dl "cover:https://mangadex.org/title/a2c1d849-af05-4bbc-b2a7-866ebb10331f/one-piece-digital-colored-comics/..." --input-pos "*" -d /data/ -vcl Japanese

Is this option just not supported for epub-volume? Instead I only get a generic text cover with the generic title (not volume title)

### What did you expect to happen ?

I expected the specific volume cover to be applied as the epub volume cover art.

### OS version

Ubuntu 22.04

### App version

mangadex-downloader v2.10.3 (https://github.com/mansuf/mangadex-downloader)
Python: 3.10.12
arch: x64
bundled executable: no

### Installation origin

PyPI (Python Package Index)

### Reproducible command

mangadex-dl https://mangadex.org/title/a2c1d849-af05-4bbc-b2a7-866ebb10331f/one-piece-digital-colored-comics -f epub-volume --language en --use-chapter-title --cover "original" -uvc -vcl Japanese --sort-by chapter --no-group-name -d /data/

**Comment by mansuf** [comment]
I forgot to put volume cover creation in `epub-volume` format, sorry about that.

Anyway, this issue has been fixed in [v3.0.0 branch](https://github.com/mansuf/mangadex-downloader/pull/80) (commit 8f81328114a420e4a3b4bedcbcc6f85ff7570b6b).

You can test it yourself by installing patched version.

If you have git, you can install it with git & pip.

```
pip uninstall mangadex-downloader
pip install git+https://github.com/mansuf/mangadex-downloader.git@8f81328114a420e4a3b4bedcbcc6f85ff7570b6b
```

If you're installing mangadex-downloader from github releases, you can download the patched version in here:

https://github.com/mansuf/mangadex-downloader/actions/runs/7261094464

The download files are available in "artifacts" section

If you have a problem or issue, just let me know 👍
