### ISSUE TITLE
Failed to find volume cover for volume "X". Falling back to manga cover...

### ISSUE THREAD

**Issue by NidokingMaster** [mansuf/mangadex-downloader#96]
### What happened ?

It seems that the latest version of mangadex-dl can't find the volume covers anymore, although they are present on mangadex.
Tried with 2 different series, same result (eg https://mangadex.org/title/0c1b0c09-d6af-4ade-9e6f-a4068025ae27/umi-no-misaki )

### What did you expect to happen ?

Maybe mangadex changed their website layout for volume covers so that mangadex-dl can't find them and always falls back to manga series cover, when the volume cover should be used.

### OS version

Windows 11

### App version

2.10.3 (x64)

### Installation origin

Github releases

### Reproducible command

mangadex-dl.exe "https://mangadex.org/title/0c1b0c09-d6af-4ade-9e6f-a4068025ae27/umi-no-misaki" --use-volume-cover --use-chapter-cover --language "German" --save-as "cbz-volume"

**Comment by mansuf** [comment]
It's a Japanese covers, you must use `--volume-cover-language Japanese` in order to get these covers. By default mangadex providing volume covers with their respective locale. And mangadex-dl follow the locale from `--language` value by default, so if you set it to `German` (from your reproducible command), it would search volume covers in German locale. These features is exist because someone complaining about volume covers getting randomized locale #66 . 

![image](https://github.com/mansuf/mangadex-downloader/assets/43638783/3b7e4789-427a-4481-9754-e1114b110ce4)
