### ISSUE TITLE
Download tracker deletes volumes and does not upgrade new chapters

### ISSUE THREAD

**Issue by Razzeli** [mansuf/mangadex-downloader#98]
### What happened ?

Hi, currently I have an issue with the 3.0 test version, where when using download tracker, it always deletes the first two already downloaded volumes, and then redownloads them again. The rest of the volumes are skipped, however it did not download the latest chapter to update the latest volume. It seems to do it with several (all?) mangas, always deleting the first two volumes.

The latest stable version (v2.10.3) works as intended, but there I guess I couldn't use my own volume names when downloading.

### What did you expect to happen ?

Skip all the previous volumes, since nothing has changed in them, and download the latest chapter when it was added to the latest volume.

### OS version

Windows 11

### App version

It says the following, but I downloaded it from here: https://github.com/mansuf/mangadex-downloader/actions/runs/8036099722

mangadex-downloader v2.10.3 (https://github.com/mansuf/mangadex-downloader)
Python: 3.10.11
arch: x64
bundled executable: yes

### Installation origin

Github releases

### Installation origin (other sources)

https://github.com/mansuf/mangadex-downloader/actions/runs/8036099722

### Reproducible command

mangadex-dl https://mangadex.org/title/e1e38166-20e4-4468-9370-187f985c550e/mato-seihei-no-slave --language "en" --use-volume-cover --volume-cover-language "ja" --no-group-name --delay-requests 0.2 --save-as cbz-volume --path "Y:/Unsorted_Mangadex_E/{manga.title}" --filename-volume "{manga.title} Vol. {volume}{file_ext}"

**Comment by mansuf** [comment]
**Note**: This patch contain migrations for download tracker, your download tracker database will be migrated to a new version. So i suggest you to backup downloaded manga before testing it.

This has been fixed in commit [c08f95c in v3.0.0 branch](https://github.com/mansuf/mangadex-downloader/commit/c08f95c698c95543f6c07b4d77686e20264f2ce5). You can try install the patched version from [here in "artifacts" section](https://github.com/mansuf/mangadex-downloader/actions/runs/8415702783) when the status is success. 

If you have any problem related to this issue, please let me know 👍.
